import { Theme } from './types';

export const themes: Theme[] = [
  // Daily Themes
  {
    id: 'tuesday',
    name: 'Default Green',
    category: 'daily',
    fontHeader: "'Playfair Display', serif",
    fontBody: "'Roboto', sans-serif",
    colors: {
      background: 'linear-gradient(135deg, #e0e8e2 0%, #d1dbd6 100%)',
      cardBackground: 'rgba(255, 255, 255, 0.5)',
      textPrimary: '#2d3748',
      textSecondary: '#4a5568',
      header: '#2f855a',
      cardBorder: '1px solid rgba(255, 255, 255, 0.3)',
      cardBoxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    },
  },
  {
    id: 'monday',
    name: 'Calm Blue',
    category: 'daily',
    fontHeader: "'Montserrat', sans-serif",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: 'linear-gradient(to top, #e0e8f0 0%, #d1e0f0 100%)',
      cardBackground: 'rgba(255, 255, 255, 0.6)',
      textPrimary: '#2d3748',
      textSecondary: '#4a5568',
      header: '#1a365d',
    },
  },
  {
    id: 'wednesday',
    name: 'Warm Yellow',
    category: 'daily',
    fontHeader: "'Lobster', cursive",
    fontBody: "'Roboto', sans-serif",
    colors: {
      background: 'linear-gradient(to right, #fef3c7, #fde68a)',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#422006',
      textSecondary: '#6b4618',
      header: '#92400e',
    },
  },
  {
    id: 'thursday',
    name: 'Toasty Orange',
    category: 'daily',
    fontHeader: "'Bangers', cursive",
    fontBody: "'Montserrat', sans-serif",
    colors: {
      background: 'linear-gradient(180deg, #ffedd5 0%, #fed7aa 100%)',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#432818',
      textSecondary: '#6f4e37',
      header: '#78350f',
    },
  },
  {
    id: 'friday',
    name: 'Vibrant Purple',
    category: 'daily',
    fontHeader: "'Playfair Display', serif",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: 'linear-gradient(to bottom right, #fae8ff, #e9d5ff)',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#4c1d95',
      textSecondary: '#6d28d9',
      header: '#5b21b6',
    },
  },
  {
    id: 'saturday',
    name: 'Saturday Sunset',
    category: 'daily',
    fontHeader: "'Dancing Script', cursive",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: 'linear-gradient(to bottom, #fca5a5, #f9a8d4, #c4b5fd)',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#881337',
      textSecondary: '#be123c',
      header: '#9f1239',
      cardBorder: '1px solid rgba(255, 255, 255, 0.2)',
    },
  },
  {
    id: 'sunday',
    name: 'Sunday Brunch',
    category: 'daily',
    fontHeader: "'Playfair Display', serif",
    fontBody: "'Roboto', sans-serif",
    colors: {
      background: '#f5f5f4',
      cardBackground: 'rgba(255, 255, 255, 0.8)',
      textPrimary: '#1c1917',
      textSecondary: '#57534e',
      header: '#78716c',
      cardBorder: '1px solid #e7e5e4',
    },
  },

  // Palette Themes
  {
    id: 'midnight',
    name: 'Midnight Mode',
    category: 'palette',
    fontHeader: "'Montserrat', sans-serif",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: 'linear-gradient(to top, #1f2937, #111827)',
      cardBackground: 'rgba(55, 65, 81, 0.7)',
      textPrimary: '#f9fafb',
      textSecondary: '#d1d5db',
      header: '#93c5fd',
      cardBorder: '1px solid rgba(147, 197, 253, 0.3)',
      cardBoxShadow: '0 0 10px rgba(147, 197, 253, 0.1)',
    },
  },
  {
    id: 'graphite',
    name: 'Graphite Night',
    category: 'palette',
    fontHeader: "'Roboto', sans-serif",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: '#18181b',
      cardBackground: 'rgba(39, 39, 42, 0.8)',
      textPrimary: '#f4f4f5',
      textSecondary: '#a1a1aa',
      header: '#22c55e',
      cardBorder: '1px solid #22c55e',
      cardBoxShadow: '0 0 12px rgba(34, 197, 94, 0.3)',
    },
  },
  {
    id: 'deep_forest',
    name: 'Deep Forest',
    category: 'palette',
    fontHeader: "'Playfair Display', serif",
    fontBody: "'Roboto', sans-serif",
    colors: {
      background: 'linear-gradient(135deg, #064e3b, #047857)',
      cardBackground: 'rgba(5, 150, 105, 0.2)',
      textPrimary: '#ecfdf5',
      textSecondary: '#a7f3d0',
      header: '#6ee7b7',
    },
  },
  {
    id: 'oceanic',
    name: 'Oceanic Teal',
    category: 'palette',
    fontHeader: "'Lobster', cursive",
    fontBody: "'Montserrat', sans-serif",
    colors: {
      background: '#f0f9ff',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#083344',
      textSecondary: '#155e75',
      header: '#0e7490',
    },
  },
  {
    id: 'crimson',
    name: 'Classic Crimson',
    category: 'palette',
    fontHeader: "'Playfair Display', serif",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: '#fef2f2',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#7f1d1d',
      textSecondary: '#b91c1c',
      header: '#991b1b',
    },
  },
  {
    id: 'earthy',
    name: 'Earthy Brown',
    category: 'palette',
    fontHeader: "'Montserrat', sans-serif",
    fontBody: "'Roboto', sans-serif",
    colors: {
      background: 'linear-gradient(to bottom, #fdf8f6, #f8f0ec)',
      cardBackground: 'rgba(255, 255, 255, 0.6)',
      textPrimary: '#422006',
      textSecondary: '#78350f',
      header: '#9a3412',
    },
  },
  {
    id: 'slate',
    name: 'Slate Gray',
    category: 'palette',
    fontHeader: "'Roboto', sans-serif",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: '#f1f5f9',
      cardBackground: 'rgba(255, 255, 255, 0.8)',
      textPrimary: '#1e293b',
      textSecondary: '#475569',
      header: '#334155',
    },
  },
  {
    id: 'pastel',
    name: 'Pastel Dreams',
    category: 'palette',
    fontHeader: "'Dancing Script', cursive",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: 'linear-gradient(45deg, #eff6ff, #e0f2fe, #dbeafe, #c7d2fe, #ddd6fe)',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#5b21b6',
      textSecondary: '#9333ea',
      header: '#a855f7',
    },
  },
  {
    id: 'cherry_blossom',
    name: 'Cherry Blossom',
    category: 'palette',
    fontHeader: "'Playfair Display', serif",
    fontBody: "'Montserrat', sans-serif",
    colors: {
      background: '#fff1f2',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#831843',
      textSecondary: '#be185d',
      header: '#db2777',
    },
  },
  {
    id: 'royal_gold',
    name: 'Royal Gold',
    category: 'palette',
    fontHeader: "'Playfair Display', serif",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: '#365314',
      cardBackground: 'rgba(255, 255, 255, 0.05)',
      textPrimary: '#f7fee7',
      textSecondary: '#ca8a04',
      header: '#facc15',
      cardBorder: '1px solid #ca8a04'
    },
  },

  // Holiday Themes
  {
    id: 'holiday-valentines',
    name: "Valentine's",
    category: 'holiday',
    fontHeader: "'Dancing Script', cursive",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: 'linear-gradient(135deg, #fff1f2, #ffe4e6)',
      cardBackground: 'rgba(255, 255, 255, 0.8)',
      textPrimary: '#881337',
      textSecondary: '#be123c',
      header: '#dc2626',
    },
  },
  {
    id: 'holiday-stpatricks',
    name: "St. Patrick's",
    category: 'holiday',
    fontHeader: "'Lobster', cursive",
    fontBody: "'Roboto', sans-serif",
    colors: {
      background: 'linear-gradient(to right, #dcfce7, #bbf7d0)',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#14532d',
      textSecondary: '#166534',
      header: '#ca8a04',
    },
  },
  {
    id: 'holiday-easter',
    name: 'Easter',
    category: 'holiday',
    fontHeader: "'Dancing Script', cursive",
    fontBody: "'Montserrat', sans-serif",
    colors: {
      background: 'linear-gradient(to bottom, #eff6ff, #dbeafe)',
      cardBackground: 'rgba(255, 255, 255, 0.8)',
      textPrimary: '#6d28d9',
      textSecondary: '#9333ea',
      header: '#f9a8d4',
    },
  },
  {
    id: 'holiday-july4',
    name: 'July 4th',
    category: 'holiday',
    fontHeader: "'Bangers', cursive",
    fontBody: "'Roboto', sans-serif",
    colors: {
      background: '#f1f5f9',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#1e3a8a',
      textSecondary: '#475569',
      header: '#b91c1c',
      cardBorder: '2px dashed #1e3a8a',
    },
  },
  {
    id: 'holiday-halloween',
    name: 'Halloween',
    category: 'holiday',
    fontHeader: "'Creepster', cursive",
    fontBody: "'Roboto', sans-serif",
    colors: {
      background: 'linear-gradient(to top, #18181b, #4a044e)',
      cardBackground: 'rgba(39, 39, 42, 0.8)',
      textPrimary: '#f4f4f5',
      textSecondary: '#a1a1aa',
      header: '#ea580c',
      cardBorder: '1px solid #ea580c',
      cardBoxShadow: '0 0 15px #ea580c',
    },
  },
  {
    id: 'holiday-thanksgiving',
    name: 'Thanksgiving',
    category: 'holiday',
    fontHeader: "'Playfair Display', serif",
    fontBody: "'Lato', sans-serif",
    colors: {
      background: 'linear-gradient(to bottom, #fff7ed, #fed7aa)',
      cardBackground: 'rgba(255, 255, 255, 0.8)',
      textPrimary: '#78350f',
      textSecondary: '#9a3412',
      header: '#c2410c',
    },
  },
  {
    id: 'holiday-christmas',
    name: 'Christmas',
    category: 'holiday',
    fontHeader: "'Dancing Script', cursive",
    fontBody: "'Roboto', sans-serif",
    colors: {
      background: '#f0fdf4',
      cardBackground: 'rgba(255, 255, 255, 0.7)',
      textPrimary: '#14532d',
      textSecondary: '#166534',
      header: '#dc2626',
      cardBorder: '1px solid #dc2626',
    },
  },
  {
    id: 'holiday-newyears',
    name: "New Year's",
    category: 'holiday',
    fontHeader: "'Lobster', cursive",
    fontBody: "'Montserrat', sans-serif",
    colors: {
      background: 'linear-gradient(to bottom, #1f2937, #111827)',
      cardBackground: 'rgba(55, 65, 81, 0.7)',
      textPrimary: '#f9fafb',
      textSecondary: '#d1d5db',
      header: '#facc15',
      cardBoxShadow: '0 0 20px rgba(250, 204, 21, 0.4)',
    },
  }
];
